### ISSUE TITLE
Stale text box focus frame

### ISSUE THREAD

**Issue by kud1ing** [MrGibus/Druid-7guis#1]
Maybe this is a druid issue? Sometimes the textbook focus frame is not reset on Mac:

<img width="710" alt="Bildschirmfoto 2020-11-19 um 16 27 34" src="https://user-images.githubusercontent.com/391975/99686967-672d3e00-2a84-11eb-87cf-575405808b8e.png">

**Comment by MrGibus** [comment]
It's a druid issue with 0.6 and has been fixed already from what I can tell.
If you run the druid styled_text example between 0.6 release and the current rep you should notice the issue goes away.

**Comment by kud1ing** [comment]
Thanks.
